{% set name = "plant-isce3" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/isce-framework/plant-isce3/archive/v{{ version }}.tar.gz
  sha256: d9129b78903adb38845ae70e4a235fa7bd9787a928acc0f98e9a0b3ef8b5f307

build:
  entry_points:
    - plant_isce3_info = plant_isce3.plant_isce3_info:main
    - plant_isce3_geocode = plant_isce3.plant_isce3_geocode:main
    - plant_isce3_polygon = plant_isce3.plant_isce3_polygon:main
    - plant_isce3_topo = plant_isce3.plant_isce3_topo:main
    - plant_isce3_util = plant_isce3.plant_isce3_util:main
    - plant_isce3_filter = plant_isce3.plant_isce3_filter:main
    - plant_isce3_resample = plant_isce3.plant_isce3_resample:main
    - plant_isce3_runconfig = plant_isce3.plant_isce3_runconfig:main
    - plant_isce3_batch_processing = plant_isce3.plant_isce3_batch_processing:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.25.2
    - gdal >=3.8
    - isce3 >=0.25.0
    - plant >=0.8.0
    - libnetcdf
    - h5py
    - matplotlib-base
    - scipy
    - s1reader >=0.2.0
    - boto3
    - libgdal-hdf5
    - libgdal-netcdf
    - pyre >=1.12.5

test:
  imports:
    - plant_isce3
  commands:
    - plant_isce3_info --help
    - plant_isce3_geocode --help
    - plant_isce3_polygon --help
    - plant_isce3_topo --help
    - plant_isce3_util --help
    - plant_isce3_filter --help
    - plant_isce3_resample --help
    - plant_isce3_runconfig --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/isce-framework/plant-isce3
  summary: 'PLAnT-ISCE3: Polarimetric Interferometric Lab and Analysis Tool (PLAnT) scripts for the InSAR Scientific Computing Environment 3 (ISCE3)'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gshiroma
