{% set name = "plant-isce3" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/isce-framework/plant-isce3/archive/v{{ version }}.tar.gz
  sha256: 3ca3d293179f10a99ceea1090f64350de4324cea1e186da0a08a0f21d1736132

build:
  entry_points:
    - plant_isce3_info = plant_isce3.plant_isce3_info:main
    - plant_isce3_geocode = plant_isce3.plant_isce3_geocode:main
    - plant_isce3_polygon = plant_isce3.plant_isce3_polygon:main
    - plant_isce3_topo = plant_isce3.plant_isce3_topo:main
    - plant_isce3_util = plant_isce3.plant_isce3_util:main
    - plant_isce3_resample = plant_isce3.plant_isce3_resample:main
    - plant_isce3_runconfig = plant_isce3.plant_isce3_runconfig:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.0.0
    - gdal >=3.8
    - isce3 >=0.24.5
    - plant >=0.5.5
    - libnetcdf
    - h5py
    - matplotlib-base
    - scipy
    - s1reader >=0.2.0

test:
  imports:
    - plant_isce3
  commands:
    - plant_isce3_info --help
    - plant_isce3_geocode --help
    - plant_isce3_polygon --help
    - plant_isce3_topo --help
    - plant_isce3_util --help
    - plant_isce3_resample --help
    - plant_isce3_runconfig --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/isce-framework/plant-isce3
  summary: 'PLAnT-ISCE3: Polarimetric Interferometric Lab and Analysis Tool (PLAnT) scripts for the InSAR Scientific Computing Environment 3 (ISCE3)'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gshiroma
